"""
Figure compliance audit tool.

Scans all figure generation scripts and generated PNGs to check compliance
with the 49 figure production rules, FigureRegistry tracking, and the
FigureRecipe system.

Usage:
    from mousedb.figures.audit import run_audit
    report = run_audit()

CLI:
    mousedb figures audit
    mousedb figures backfill
"""

import ast
import json
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from mousedb import MOUSEDB_ROOT, DEFAULT_FIGURES_PATH


# ============================================================================
# Script compliance checks
# ============================================================================

# Patterns we look for in source files to assess compliance
COMPLIANCE_PATTERNS = {
    "imports_mousedb_figures": [
        r"from\s+mousedb\.figures",
        r"import\s+mousedb\.figures",
    ],
    "uses_save_figure": [
        r"save_figure\s*\(",
    ],
    "uses_register": [
        r"register\s*=\s*True",
        r"registry\.register\s*\(",
        r"FigureRegistry",
    ],
    "uses_figure_legend": [
        r"FigureLegend\s*\(",
    ],
    "uses_methodology_panel": [
        r"add_methodology_panel\s*\(",
        r"methodology_text",
    ],
    "uses_cohens_d": [
        r"cohens_d",
        r"cohen",
        r"effect_size",
    ],
    "uses_canonical_palettes": [
        r"from\s+mousedb\.figures\.palettes",
        r"COHORT_COLORS",
        r"PHASE_COLORS",
        r"PELLET_PHASE_COLORS",
        r"OUTCOME_COLORS",
    ],
    "uses_inline_colors": [
        r"""['"]#[0-9a-fA-F]{6}['"]""",
    ],
    "is_figure_recipe": [
        r"class\s+\w+\(FigureRecipe\)",
        r"FigureRecipe",
    ],
    "uses_provenance_footer": [
        r"add_provenance_footer\s*\(",
    ],
    "uses_stat_bracket": [
        r"add_stat_bracket",
    ],
    "uses_validation": [
        r"validate_layout\s*\(",
        r"check_readability\s*\(",
    ],
}


def _check_patterns(source: str, patterns: List[str]) -> bool:
    """Check if any pattern matches in source."""
    for pat in patterns:
        if re.search(pat, source):
            return True
    return False


def _count_inline_colors(source: str) -> int:
    """Count inline hex color definitions (potential palette violations)."""
    return len(re.findall(r"""['"]#[0-9a-fA-F]{6}['"]""", source))


def _count_savefig_calls(source: str) -> int:
    """Count direct plt.savefig / fig.savefig calls (should use save_figure)."""
    return len(re.findall(r"\.savefig\s*\(", source))


def _count_figure_functions(source: str) -> int:
    """Estimate the number of distinct figures generated by a script."""
    # Count save_figure calls or savefig calls
    save_calls = len(re.findall(r"save_figure\s*\(", source))
    savefig_calls = len(re.findall(r"\.savefig\s*\(", source))
    return max(save_calls, savefig_calls, 1)


def audit_script(script_path: Path) -> Dict:
    """Audit a single figure generation script for compliance.

    Returns a dict with compliance flags and details.
    """
    source = script_path.read_text(encoding="utf-8", errors="replace")

    result = {
        "path": str(script_path),
        "name": script_path.name,
        "size_kb": round(script_path.stat().st_size / 1024, 1),
        "est_figures": _count_figure_functions(source),
    }

    # Check each compliance pattern
    for key, patterns in COMPLIANCE_PATTERNS.items():
        result[key] = _check_patterns(source, patterns)

    # Additional metrics
    result["inline_color_count"] = _count_inline_colors(source)
    result["direct_savefig_count"] = _count_savefig_calls(source)

    # Compute compliance score (out of 10 key checks)
    checks = [
        result.get("imports_mousedb_figures", False),
        result.get("uses_save_figure", False),
        result.get("uses_register", False),
        result.get("uses_figure_legend", False),
        result.get("uses_methodology_panel", False),
        result.get("uses_cohens_d", False),
        result.get("uses_canonical_palettes", False),
        not result.get("uses_inline_colors", True),  # inverted: no inline = good
        result.get("is_figure_recipe", False),
        result.get("uses_provenance_footer", False),
    ]
    result["compliance_score"] = sum(checks)
    result["compliance_max"] = len(checks)

    return result


# ============================================================================
# PNG compliance checks
# ============================================================================

def audit_png(png_path: Path, registered_paths: set) -> Dict:
    """Audit a single PNG figure for compliance.

    Parameters
    ----------
    png_path : Path
        Path to the PNG file.
    registered_paths : set
        Set of file paths (relative to MOUSEDB_ROOT/figures/) that are
        registered in FigureRegistry.

    Returns a dict with compliance flags.
    """
    result = {
        "path": str(png_path),
        "name": png_path.name,
        "size_kb": round(png_path.stat().st_size / 1024, 1),
    }

    # Check for JSON sidecar
    sidecar_path = png_path.with_suffix(".json")
    result["has_sidecar"] = sidecar_path.exists()

    # Parse sidecar metadata if it exists
    if result["has_sidecar"]:
        try:
            with open(sidecar_path) as f:
                meta = json.load(f)
            result["sidecar_script"] = meta.get("script", "")
            result["sidecar_has_recipe"] = meta.get("script", "").startswith("recipe:")
            result["sidecar_data_sources"] = len(meta.get("data_sources", []))
            result["sidecar_mode"] = meta.get("mode", "")
        except (json.JSONDecodeError, OSError):
            result["sidecar_script"] = ""
            result["sidecar_has_recipe"] = False
            result["sidecar_data_sources"] = 0
            result["sidecar_mode"] = ""
    else:
        result["sidecar_script"] = ""
        result["sidecar_has_recipe"] = False
        result["sidecar_data_sources"] = 0
        result["sidecar_mode"] = ""

    # Check if registered in FigureRegistry
    try:
        rel_path = str(png_path.relative_to(MOUSEDB_ROOT / "figures"))
    except ValueError:
        rel_path = str(png_path)
    result["is_registered"] = rel_path in registered_paths

    return result


# ============================================================================
# Full audit
# ============================================================================

def _get_registered_figure_paths() -> set:
    """Query FigureRegistry for all registered figure file paths."""
    try:
        from mousedb.database import get_db
        from mousedb.registry.models import FigureRecord
        db = get_db()
        with db.session() as session:
            records = session.query(FigureRecord.file_path).filter(
                FigureRecord.is_current == 1
            ).all()
            return {r.file_path for r in records if r.file_path}
    except Exception:
        return set()


def _find_figure_scripts(figures_dir: Path) -> List[Path]:
    """Find all Python scripts in the figures directory tree."""
    scripts = []
    if figures_dir.exists():
        for py_file in figures_dir.rglob("*.py"):
            # Skip __pycache__, .omc, hidden dirs
            parts = py_file.relative_to(figures_dir).parts
            if any(p.startswith(".") or p.startswith("_") or p == "__pycache__" for p in parts):
                continue
            scripts.append(py_file)
    return sorted(scripts)


def _find_figure_pngs(figures_dir: Path) -> List[Path]:
    """Find all PNG files in the figures directory tree."""
    pngs = []
    if figures_dir.exists():
        for png_file in figures_dir.rglob("*.png"):
            parts = png_file.relative_to(figures_dir).parts
            if any(p.startswith(".") or p == "__pycache__" for p in parts):
                continue
            pngs.append(png_file)
    return sorted(pngs)


def run_audit(figures_dir: Optional[Path] = None, verbose: bool = False) -> Dict:
    """Run full compliance audit on all figure scripts and PNGs.

    Parameters
    ----------
    figures_dir : Path, optional
        Root directory to scan. Defaults to MOUSEDB_ROOT / "figures".
    verbose : bool
        If True, print detailed per-file results.

    Returns
    -------
    dict
        Full audit report with scripts, pngs, and summary sections.
    """
    if figures_dir is None:
        figures_dir = DEFAULT_FIGURES_PATH

    print(f"\n{'=' * 70}")
    print("FIGURE COMPLIANCE AUDIT")
    print(f"{'=' * 70}")
    print(f"  Scanning: {figures_dir}")

    # --- Script audit ---
    scripts = _find_figure_scripts(figures_dir)
    print(f"\n  Found {len(scripts)} Python scripts in figures directory")
    print(f"  (CODE IN DATA DIRECTORY -- all should be migrated to mousedb/recipes/)")

    script_results = []
    for s in scripts:
        result = audit_script(s)
        script_results.append(result)

    if scripts:
        print(f"\n  {'Script':<45} {'Score':>6} {'Recipe':>7} {'Reg':>5} "
              f"{'Legend':>7} {'Method':>7} {'Stats':>6}")
        print(f"  {'-' * 85}")
        for r in script_results:
            score_str = f"{r['compliance_score']}/{r['compliance_max']}"
            recipe = "yes" if r["is_figure_recipe"] else "NO"
            reg = "yes" if r["uses_register"] else "NO"
            legend = "yes" if r["uses_figure_legend"] else "NO"
            method = "yes" if r["uses_methodology_panel"] else "NO"
            stats = "yes" if r["uses_cohens_d"] else "NO"
            print(f"  {r['name']:<45} {score_str:>6} {recipe:>7} {reg:>5} "
                  f"{legend:>7} {method:>7} {stats:>6}")

    # --- PNG audit ---
    registered_paths = _get_registered_figure_paths()
    pngs = _find_figure_pngs(figures_dir)
    print(f"\n  Found {len(pngs)} PNG figures")
    print(f"  FigureRegistry contains {len(registered_paths)} current entries")

    png_results = []
    for p in pngs:
        result = audit_png(p, registered_paths)
        png_results.append(result)

    # PNG summary stats
    n_with_sidecar = sum(1 for r in png_results if r["has_sidecar"])
    n_registered = sum(1 for r in png_results if r["is_registered"])
    n_recipe_sidecar = sum(1 for r in png_results if r["sidecar_has_recipe"])

    print(f"\n  PNG Compliance Summary:")
    print(f"    Has JSON sidecar     : {n_with_sidecar:>4} / {len(pngs)} "
          f"({_pct(n_with_sidecar, len(pngs))})")
    print(f"    In FigureRegistry    : {n_registered:>4} / {len(pngs)} "
          f"({_pct(n_registered, len(pngs))})")
    print(f"    Recipe-generated     : {n_recipe_sidecar:>4} / {len(pngs)} "
          f"({_pct(n_recipe_sidecar, len(pngs))})")

    # --- Overall summary ---
    total_scripts = len(scripts)
    recipe_scripts = sum(1 for r in script_results if r["is_figure_recipe"])
    registered_scripts = sum(1 for r in script_results if r["uses_register"])
    legend_scripts = sum(1 for r in script_results if r["uses_figure_legend"])
    method_scripts = sum(1 for r in script_results if r["uses_methodology_panel"])

    print(f"\n{'=' * 70}")
    print("COMPLIANCE SUMMARY")
    print(f"{'=' * 70}")
    print(f"\n  Scripts in data directory (violation): {total_scripts}")
    print(f"    Using FigureRecipe   : {recipe_scripts:>4} / {total_scripts} "
          f"({_pct(recipe_scripts, total_scripts)})")
    print(f"    Using FigureRegistry : {registered_scripts:>4} / {total_scripts} "
          f"({_pct(registered_scripts, total_scripts)})")
    print(f"    Has FigureLegend     : {legend_scripts:>4} / {total_scripts} "
          f"({_pct(legend_scripts, total_scripts)})")
    print(f"    Has methodology panel: {method_scripts:>4} / {total_scripts} "
          f"({_pct(method_scripts, total_scripts)})")

    print(f"\n  PNGs: {len(pngs)} total")
    print(f"    With sidecar         : {n_with_sidecar:>4} / {len(pngs)} "
          f"({_pct(n_with_sidecar, len(pngs))})")
    print(f"    In FigureRegistry    : {n_registered:>4} / {len(pngs)} "
          f"({_pct(n_registered, len(pngs))})")
    print(f"    Recipe-generated     : {n_recipe_sidecar:>4} / {len(pngs)} "
          f"({_pct(n_recipe_sidecar, len(pngs))})")

    if total_scripts > 0:
        print(f"\n  [!] {total_scripts} Python scripts live in data directory "
              f"(Databases/figures/).")
        print(f"      These must be migrated to mousedb/recipes/ as FigureRecipe classes.")

    n_unregistered = len(pngs) - n_registered
    if n_unregistered > 0:
        print(f"\n  [!] {n_unregistered} PNGs are not tracked in FigureRegistry.")
        print(f"      Run 'mousedb figures backfill' to register PNGs with sidecars.")

    print()

    return {
        "figures_dir": str(figures_dir),
        "scripts": script_results,
        "pngs": png_results,
        "summary": {
            "total_scripts": total_scripts,
            "recipe_scripts": recipe_scripts,
            "registered_scripts": registered_scripts,
            "legend_scripts": legend_scripts,
            "method_scripts": method_scripts,
            "total_pngs": len(pngs),
            "pngs_with_sidecar": n_with_sidecar,
            "pngs_registered": n_registered,
            "pngs_recipe_generated": n_recipe_sidecar,
        },
    }


# ============================================================================
# Backfill: register existing PNGs with sidecars into FigureRegistry
# ============================================================================

def backfill_registry(figures_dir: Optional[Path] = None,
                      dry_run: bool = False) -> Dict:
    """Register untracked PNGs that have JSON sidecars into FigureRegistry.

    Parameters
    ----------
    figures_dir : Path, optional
        Root directory to scan. Defaults to MOUSEDB_ROOT / "figures".
    dry_run : bool
        If True, report what would be registered without actually doing it.

    Returns
    -------
    dict
        Summary with counts of registered, skipped, and failed entries.
    """
    from mousedb.registry import FigureRegistry

    if figures_dir is None:
        figures_dir = DEFAULT_FIGURES_PATH

    registry = FigureRegistry()
    registered_paths = _get_registered_figure_paths()
    pngs = _find_figure_pngs(figures_dir)

    print(f"\n{'=' * 60}")
    print(f"FIGURE REGISTRY BACKFILL {'(DRY RUN)' if dry_run else ''}")
    print(f"{'=' * 60}")
    print(f"  Scanning: {figures_dir}")
    print(f"  Found {len(pngs)} PNGs, {len(registered_paths)} already registered")

    registered = 0
    skipped = 0
    failed = 0
    no_sidecar = 0

    for png_path in pngs:
        # Compute relative path
        try:
            rel_path = str(png_path.relative_to(MOUSEDB_ROOT / "figures"))
        except ValueError:
            rel_path = str(png_path)

        # Skip if already registered
        if rel_path in registered_paths:
            skipped += 1
            continue

        # Need sidecar to have any metadata
        sidecar_path = png_path.with_suffix(".json")
        if not sidecar_path.exists():
            no_sidecar += 1
            continue

        # Read sidecar
        try:
            with open(sidecar_path) as f:
                meta = json.load(f)
        except (json.JSONDecodeError, OSError):
            failed += 1
            continue

        # Infer category from directory structure
        try:
            rel_parts = png_path.relative_to(figures_dir).parts
            category = rel_parts[0] if len(rel_parts) > 1 else "uncategorized"
        except ValueError:
            category = "uncategorized"

        if dry_run:
            print(f"  Would register: {rel_path} (category={category})")
            registered += 1
            continue

        # Register
        try:
            script_name = meta.get("script", "unknown")
            data_sources = []
            for ds in meta.get("data_sources", []):
                if isinstance(ds, str):
                    data_sources.append({
                        "source_type": "csv",
                        "source_path": ds,
                    })
                elif isinstance(ds, dict):
                    data_sources.append(ds)

            accession = registry.register(
                figure_path=png_path,
                title=meta.get("title", png_path.stem),
                category=category,
                recipe_name=meta.get("script", "").replace("recipe:", "") if "recipe:" in meta.get("script", "") else None,
                data_sources=data_sources or None,
                parameters=None,
                theme="light",
                mode=meta.get("mode", "presentation"),
                dpi=meta.get("dpi", 200),
                script_name=script_name,
            )
            print(f"  Registered: {accession} <- {rel_path}")
            registered += 1
        except Exception as e:
            print(f"  [FAIL] {rel_path}: {e}")
            failed += 1

    print(f"\n  Results:")
    print(f"    Registered   : {registered}")
    print(f"    Already tracked: {skipped}")
    print(f"    No sidecar   : {no_sidecar}")
    print(f"    Failed       : {failed}")
    print()

    return {
        "registered": registered,
        "skipped": skipped,
        "no_sidecar": no_sidecar,
        "failed": failed,
        "dry_run": dry_run,
    }


# ============================================================================
# Helpers
# ============================================================================

def _pct(n: int, total: int) -> str:
    """Format percentage string."""
    if total == 0:
        return "N/A"
    return f"{n / total * 100:.0f}%"
