"""
Figure generation standards for the Connectome project.

THE RULES. These are enforced, not optional. Every figure generated by any
Connectome tool must comply with these standards.

Rules:
    1. Every figure MUST have a methodology panel explaining what it shows.
    2. Every figure MUST have a provenance line (script, data, timestamp).
    3. Every figure MUST state N (sample size).
    4. Every figure with statistics MUST state: test name, p-values,
       sample sizes, and directionality.
    5. Every figure with phases MUST define phases in the methodology panel.
    6. Every figure with inclusion/exclusion criteria MUST state them.
    7. Color palettes from mousedb.figures.palettes ONLY -- no inline colors.
    8. No top or right spines.
    9. ASCII only in print/logging output (Windows cp1252 compatibility).
   10. Theme (light/dark/print) is a parameter, not hardcoded. Light is default
       for publication/posters; dark is available for presentations.
"""

import matplotlib
import matplotlib.pyplot as plt


# =============================================================================
# DPI standards
# =============================================================================

DPI = {
    "draft": 100,
    "presentation": 200,
    "publication": 300,
    "print": 600,
}


# =============================================================================
# Font standards
# =============================================================================

FONT = {
    "family": "sans-serif",
    "sans_serif_list": ["Segoe UI", "Arial", "Helvetica", "DejaVu Sans"],
    "size_publication": 10,
    "size_presentation": 12,
    "title_weight": "bold",
}


# =============================================================================
# Required elements checklist (used by protocol.py for validation)
# =============================================================================

REQUIRED_ELEMENTS = [
    "methodology_panel",
    "provenance_line",
    "sample_size_stated",
]


# =============================================================================
# Theme system (light / dark / print)
# =============================================================================

THEMES = {
    "light": {
        "background": "#FFFFFF",
        "text": "#333333",
        "text_secondary": "#666666",
        "grid": "#E0E0E0",
        "spine": "#333333",
        "methodology_bg": "#F8F8F8",
        "methodology_border": "#CCCCCC",
        "methodology_text": "#333333",
        "legend_bg": "#FFFFFF",
        "legend_border": "#CCCCCC",
    },
    "dark": {
        "background": "#1A1A1A",
        "text": "#E0E0E0",
        "text_secondary": "#999999",
        "grid": "#333333",
        "spine": "#888888",
        "methodology_bg": "#2A2A2A",
        "methodology_border": "#444444",
        "methodology_text": "#CCCCCC",
        "legend_bg": "#2A2A2A",
        "legend_border": "#444444",
    },
    "print": {
        "background": "#FFFFFF",
        "text": "#000000",
        "text_secondary": "#333333",
        "grid": "#CCCCCC",
        "spine": "#000000",
        "methodology_bg": "#F0F0F0",
        "methodology_border": "#999999",
        "methodology_text": "#000000",
        "legend_bg": "#FFFFFF",
        "legend_border": "#999999",
    },
}

# Current active theme (set by apply_style)
_active_theme = "light"


def get_theme(theme=None):
    """Get theme colors dict. Uses active theme if none specified."""
    return THEMES[theme or _active_theme]


# =============================================================================
# Matplotlib rcParams presets
# =============================================================================

def _build_base_rcparams(theme="light"):
    """Build base rcParams for a given theme."""
    t = THEMES[theme]
    return {
        "figure.facecolor": t["background"],
        "axes.facecolor": t["background"],
        "savefig.facecolor": t["background"],
        "text.color": t["text"],
        "axes.labelcolor": t["text"],
        "xtick.color": t["text"],
        "ytick.color": t["text"],
        "font.family": "sans-serif",
        "font.sans-serif": ["Segoe UI", "Arial", "Helvetica", "DejaVu Sans"],
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.edgecolor": t["spine"],
        "axes.linewidth": 1.0,
        "axes.grid": False,
        "grid.alpha": 0.15,
        "grid.linewidth": 0.5,
        "grid.color": t["grid"],
        "legend.framealpha": 0.85,
        "legend.edgecolor": t["legend_border"],
        "legend.facecolor": t["legend_bg"],
    }


def _build_publication_rcparams(theme="light"):
    return {
        **_build_base_rcparams(theme),
        "font.size": 10,
        "axes.titlesize": 11,
        "axes.labelsize": 10,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
        "legend.fontsize": 9,
        "figure.dpi": 300,
        "savefig.dpi": 300,
    }


def _build_presentation_rcparams(theme="light"):
    return {
        **_build_base_rcparams(theme),
        "font.size": 12,
        "axes.titlesize": 16,
        "axes.labelsize": 13,
        "xtick.labelsize": 11,
        "ytick.labelsize": 11,
        "legend.fontsize": 10,
        "figure.dpi": 200,
        "savefig.dpi": 200,
    }


# Pre-built for backward compatibility (light theme)
_BASE_RCPARAMS = _build_base_rcparams("light")
RCPARAMS_PUBLICATION = _build_publication_rcparams("light")
RCPARAMS_PRESENTATION = _build_presentation_rcparams("light")


def apply_style(mode="presentation", theme="light"):
    """Apply Connectome figure style to matplotlib.

    Parameters
    ----------
    mode : str
        One of "publication", "presentation". Controls font sizes and DPI.
    theme : str
        One of "light", "dark", "print". Controls colors and backgrounds.
    """
    global _active_theme
    _active_theme = theme

    if mode == "publication":
        params = _build_publication_rcparams(theme)
    elif mode == "presentation":
        params = _build_presentation_rcparams(theme)
    else:
        raise ValueError(f"Unknown style mode: {mode!r}. Use 'publication' or 'presentation'.")

    plt.rcParams.update(params)
